### PR TITLE
add support for tags

### PR DESCRIPTION
**Pull request by lunarfs**
I want to build 3.10 but it is not in origin but tags, added support for building tags.
I am not entirely sure about the argument counting.. up for suggestions on how to improve that

### CODE REVIEW

**Comment by spodkowinski** [comment]
It's probably easier to simply get rid of the `origin/` prefix and leave it to the caller to specify the correct path.

**Comment by lunarfs** [comment]
@spodkowinski ok, i have updated the PR and added some further description, let me know what you think

**Comment by spodkowinski** [comment]
This is probably more complicated than it has to be. Why not simply use the path as specified by the user, instead of having two use cases for either branches or tags? If you get back to the current version in master and just remove `origin/`, wouldn't that solve the issue?

**Comment by lunarfs** [comment]
@spodkowinski yes, that is a much nicer fix, thanks for the input.

**Comment by spodkowinski** [comment]
I've merged your patch, except for the readme changes, as branches can be references without specifying origin as remote. Thanks for your contribution, @lunarfs!

**Pull request closed without merging**
