### PR TITLE
Add Ubuntu 19.10 with JDK11 Image

### PR DESCRIPTION
**Pull request by nastra**
This image includes Python 3.6+3.7+3.8 installations in case C* wants to
perform testing with multiple Python versions.

### CODE REVIEW

**Comment by michaelsembwever** [comment]
Thanks @nastra 

Some questions… (i'm not so knowledgable on the use of these images)
- is there a corresponding circleci yaml patch to this? and/or a jira ticket?
- is there any CI for building these images? 
- is @spodkowinski still the maintainer? and is there a better dockerhub account to use than spod? eg https://hub.docker.com/u/apache ?

**Comment by nastra** [comment]
@michaelsembwever thanks for checking the PR out.

> is there a corresponding circleci yaml patch to this? and/or a jira ticket?

Yes, I'm basically working on https://issues.apache.org/jira/browse/CASSANDRA-15659 and in order to test it, I need a Docker image with newer Python versions installed. I talked to @spodkowinski about it on Slack.
The C* is still in progress, so it's possible that the contents of this PR might change a bit. I also haven't run any tests with this particular Docker image, but results will follow shortly.

> is @spodkowinski still the maintainer? and is there a better dockerhub account to use than spod? eg https://hub.docker.com/u/apache ?

I don't know. I was hoping that we would be able to find out while reviewing this PR.

**Comment by spodkowinski** [comment]
> and is there a better dockerhub account to use than spod? eg https://hub.docker.com/u/apache ?

I think it would be possible to open a ticket with Infra and ask them for creating a repo for us and add some committers as admins. However, given that our image is based on other external images and is not supposed to be used by anyone except us, I'm wondering if the extra work is really worth it, instead of just publishing to a user repo.

**Comment by nastra** [comment]
Ok I pushed the docker images to https://hub.docker.com/u/nastra and I'm running now tests with them as part of https://issues.apache.org/jira/browse/CASSANDRA-15659 in https://app.circleci.com/pipelines/github/nastra/cassandra/15/workflows/fd0a086f-a00b-4eea-8dc4-70aac50cba6a

**Comment by nastra** [comment]
@spodkowinski @michaelsembwever this PR would be ready for a review. Related tickets are https://issues.apache.org/jira/browse/CASSANDRA-15659 and https://issues.apache.org/jira/browse/CASSANDRA-15573

**Comment by michaelsembwever** [comment]
remember to remove the `--no-site-packages` here as well…

**Comment by nastra** [comment]
> remember to remove the --no-site-packages here as well…

@michaelsembwever in which file specifically do you mean? I removed that already when creating the new Docker files. I didn't want to adjust the existing ones (beside the typo fixes) as the existing  docker files can't be built anyway.

**Review by michaelsembwever — APPROVED** [review]

**Pull request merged**
