### PR TITLE
Clean up any "org.apache.cassandra" processes that are left dangling after jobs complete (if the agent is otherwise idle)

### PR DESCRIPTION
**Pull request by michaelsembwever**
@smiklosovic 

tested in https://ci-cassandra.apache.org/view/patches/job/Cassandra-devbranch-test/575/ 

example of pkill being invoked in https://ci-cassandra.apache.org/view/patches/job/Cassandra-devbranch-test/575/jdk=jdk_1.8_latest,label=cassandra,split=6/console

### CODE REVIEW

**Comment by smiklosovic** [comment]
thanks @michaelsembwever , good to know.

**Comment by smiklosovic** [comment]
+1

**Comment by michaelsembwever** [comment]
merged manually with https://github.com/apache/cassandra-builds/commit/d2d0d766c09ccf9351eb988dc6f082eef16515da

**Comment by michaelsembwever** [comment]
Follow up commit required with 9a0af58

**Pull request closed without merging**
