### PR TITLE
SHAs printed need to be consistent (abbreviated can vary in length), see jenkins-dsl/print-shas.sh

### PR DESCRIPTION
**Pull request by michaelsembwever**

### CODE REVIEW

**Comment by michaelsembwever** [comment]
@bereng, are you interested in reviewing this? (remember we discovered the print shas was broken and the fix was to print full shas)

**Comment by bereng** [comment]
Hi @michaelsembwever,

I'd need some context here. What problem are we trying to solve? Just the cosmetics of making SHAs consistent or are we actually making them consistent so we don't barf/log the same SHA for MBs at the end of each run?

**Comment by michaelsembwever** [comment]
The `print-shas.ah` script checks that only one sha for each repository was used in all the builds in the pipeline. If more than one per repo was found, it prints all of them.

Previously we were logging abbreviated SHAs. These are variable in length. This resulted in more than on sha per repo being identified and full print outs occurring (despite the real SHAs being only one per repo). Switching to logging full sha instead of abbreviated sha is expected to solve this problem.

**Comment by bereng** [comment]
Ok yeah, thanks. I wanted to make sure I was following the train of thought. LGTM +1

**Comment by michaelsembwever** [comment]
Working (finally)
```

15:49:32  [Pipeline] sh
15:49:33  + ./cassandra-builds/jenkins-dsl/print-shas.sh
15:49:33  The folllowing SHAs were consistently used in all jobs in the pipeline…
15:49:34  cassandra-builds: 33178a6631f4de5c6c6773dfb9bcd8035d47b014 Mick Semb Wever Sun May 22 14:58:39 2022 +0200 In jenkins, throttle pipeline jobs (except one primary release branch pipeline)
15:49:34  cassandra-dtest: bd393785ceede6516919aa53f7721eb0557b7827 Brandon Williams Wed May 18 14:18:52 2022 -0500 Ignore failing slices on 2.2 for auth
15:49:34  cassandra: 6f6adbb47703405fd0428c0f3be464f404666ab3 Brandon Williams Wed Apr 20 10:57:29 2022 -0500 circle, do not merge.
```

**Comment by bereng** [comment]
Yessssssssss! :muscle:

**Pull request merged**
